### ISSUE TITLE
An alternative package

### ISSUE THREAD

**Issue by davidhu2000** [kirillDanshin/halogenium#6]
Due to the lack of maintenance of the halogen repo, I migrated all the code to a new repo and added some more spinners, i didn't realize this repo existed. For anyone who is interested, come check out my version. I'll be actively maintaining it. 

Demo: http://www.davidhu.io/react-spinners/

Github: https://github.com/davidhu2000/react-spinners

**Comment by kirillDanshin** [comment]
Hi @davidhu2000
I just check out your package and seen that ClimbingBoxLoader makes you feel nervous. That's happen because you getting back the box and creating feeling like whole thing is broken and trying to initialize again and again, instead of creating another one and climbing that one too to create feeling that something works as expected right now. Check it out, maybe it needs to be fixed. Anyway, looks good to me, I leave this issue open for now, but also glad to see PRs here by anyone including you :)
